name:                evaluator

dependencies:
- base >= 4.7 && < 5
- containers
- gloss
- process
- http-conduit >= 2.3
- utf8-string >= 1.0
- bytestring

library:
  source-dirs: lib

executables:
  evaluator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -optc-O2
    - -Wall
    dependencies:
    - evaluator
