name:                evaluator

dependencies:
- base >= 4.7 && < 5
- containers
- gloss

library:
  source-dirs: lib

executables:
  evaluator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -optc-O2
    dependencies:
    - evaluator
